name: Create Tag Version

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global http.sslVerify false
            git config --global pull.ff only
            git remote rm origin
            git remote add origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            git checkout -B "${{ github.ref_name }}"
        
      - name: Create new tag
        run: |
            git tag -l
            NEW_TAG=$(git tag | egrep "^v(\d.\d.\d*)$" | awk '{gsub(/^v/,"");}1' | sort --version-sort | tail -n 1 | awk 'BEGIN { FS="." } {newMinor=$3+1} { printf "%s.%s.%s", $1, $2, newMinor }')
            echo "NEW_TAG=${NEW_TAG}"
            git tag v$NEW_TAG -m "🤖 Tagged by GitHub Actions" -m "For further reference see $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
            git push origin v$NEW_TAG --no-verify
