on:
  push:
      branches:
          - master

jobs:
  increment-version:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Get next version
          uses: reecetech/version-increment@2024.4.3
          id: version
          with:
            scheme: semver
            increment: patch

        - name: Build image
          uses: docker/build-push-action@v2
          with:
            push: false
            tags: "innoboxrr/video-processor:${{ steps.version.outputs.version }}"
            context: .