on:
  push:
      branches:
          - master

jobs:
  increment-version:
      runs-on: ubuntu-latest

      steps:
      - name: Auto increment tag
        id: tag
        uses: sophiware/actions-auto-increment-tag@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Container tag
        run: |
          docker tag innoboxrr/video-processor innoboxrr/video-processor:${{ steps.tag.outputs.tag }}